export const SAP_ASCTD_DOC_TYPES = {
  INVOICE: 'IM_INVOICE_NUMBER',
  CUSTOM_INVOICE: 'IM_INVOICE_NUMBER',
  DELIVERY: 'IM_DELIVERY_NUMBER',
  PURCHASE_ORDER: 'IM_PO_NUMBER',
  SOA: 'IM_SOA_NUMBER',
};
